<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaymentMethodsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $paymentMethods = [
            ['1','Abra','0','1'],
            ['1','AdvCash','0','1'],
            ['1','Afriex','0','1'],
            ['1','Airline Tickets','0','1'],
            ['1','AirPay','0','1'],
            ['1','Airtel Money','0','1'],
            ['1','AirTM','0','1'],
            ['1','ApplePay','1','1'],
            ['1','AstroPay Direct','0','1'],
            ['1','AZA Finance','0','1'],
            ['1','Azimo','0','1'],
            ['1','Barter from Flutterwave','0','1'],
            ['1','Bhim','0','1'],
            ['1','Bill payment','0','1'],
            ['1','BitLipa','0','1'],
            ['1','Bitsika','0','1'],
            ['1','Bitwallet','0','1'],
            ['1','Bkash E-Wallet','0','1'],
            ['1','Bnext','0','1'],
            ['1','Bunq Transfer','0','1'],
            ['1','Capital One 360 P2P Payment','0','1'],
            ['1','Carbon','0','1'],
            ['1','Cash app','0','1'],
            ['1','CashU','0','1'],
            ['1','Cellulant','0','1'],
            ['1','Chase Quickpay','0','1'],
            ['1','Chime instant transfers','0','1'],
            ['1','ChimpChange Mobile Banking','0','1'],
            ['1','Chipper Cash','0','1'],
            ['1','CIB smart wallet','0','1'],
            ['1','Circle Pay','0','1'],
            ['1','Current Pay','0','1'],
            ['1','Ding Connect','0','1'],
            ['1','DotPay Wallet','0','1'],
            ['1','E-zwich','0','1'],
            ['1','Easypaisa','0','1'],
            ['1','eCheck','0','1'],
            ['1','EcoCash','0','1'],
            ['1','ecoPayz','0','1'],
            ['1','EMQ Send','0','1'],
            ['1','ePay','0','1'],
            ['1','Equitel Mobile Money','0','1'],
            ['1','Esewa','0','1'],
            ['1','Etisalat cash','0','1'],
            ['1','Eversend','0','1'],
            ['1','Expresspay','0','1'],
            ['1','Facebook Messenger Payment','0','1'],
            ['1','FasaPay Online Payment','0','1'],
            ['1','Flashpay Netspend','0','1'],
            ['1','Fliqpay','0','1'],
            ['1','FNB E-WALLET','0','1'],
            ['1','Freecharge','0','1'],
            ['1','GCash','1','1'],
            ['1','Getcarbon','0','1'],
            ['1','Gobank Money Transfer','0','1'],
            ['1','Google Pay','0','1'],
            ['1','GrabPay','0','1'],
            ['1','GönderAL','0','1'],
            ['1','Hello Paisa','0','1'],
            ['1','Hilton HHonors Points','0','1'],
            ['1','Hubtel','0','1'],
            ['1','iCard','0','1'],
            ['1','Ininal','0','1'],
            ['1','Interac e-Transfer','0','1'],
            ['1','JazzCash','0','1'],
            ['1','JioMoney','0','1'],
            ['1','KaKaoPay','0','1'],
            ['1','Kurepay','0','1'],
            ['1','Lemonade Finance','0','1'],
            ['1','Line Pay','0','1'],
            ['1','LiqPay','0','1'],
            ['1','M-Pesa','1','1'],
            ['1','mCash Mobile Payment','0','1'],
            ['1','Mercado Pago','0','1'],
            ['1','MobiKwik Wallet','0','1'],
            ['1','Mobile Recharge','0','1'],
            ['1','MobilePay','0','1'],
            ['1','Mobivi','0','1'],
            ['1','Moca','0','1'],
            ['1','MODO','0','1'],
            ['1','Momo','0','1'],
            ['1','Monese Online Transfer','0','1'],
            ['1','Movii','0','1'],
            ['1','mPayVN','0','1'],
            ['1','MTN Mobile Money','0','1'],
            ['1','Mukuru','0','1'],
            ['1','N26','0','1'],
            ['1','NBE Phone cash','0','1'],
            ['1','Neteller','0','1'],
            ['1','NganLuong','0','1'],
            ['1','OkPay','0','1'],
            ['1','Ononpay','0','1'],
            ['1','Opal Transfer','0','1'],
            ['1','Orange money','0','1'],
            ['1','Other Online Wallets','0','1'],
            ['1','Oxigen Wallet','0','1'],
            ['1','Ozow','0','1'],
            ['1','Paga Wallet','0','1'],
            ['1','Pago Fácil','0','1'],
            ['1','Papara','0','1'],
            ['1','Payeer','0','1'],
            ['1','PayM','0','1'],
            ['1','PayMaya Wallet','0','1'],
            ['1','PayMe','0','1'],
            ['1','Payoneer','0','1'],
            ['1','Payoo','0','1'],
            ['1','PayPal','1','1'],
            ['1','Paypower','0','1'],
            ['1','Paysend.com','0','1'],
            ['1','Paysera Money Transfer','0','1'],
            ['1','PaySon','0','1'],
            ['1','Paytm Online Wallet','0','1'],
            ['1','PayU Wallet','0','1'],
            ['1','Payza','0','1'],
            ['1','PayZapp','0','1'],
            ['1','Perfect Money','0','1'],
            ['1','Pesalink','0','1'],
            ['1','PhonePe','0','1'],
            ['1','Piggyvest','0','1'],
            ['1','PIM','0','1'],
            ['1','Pingit','0','1'],
            ['1','Pintu','0','1'],
            ['1','PlusGirot','0','1'],
            ['1','Pockit - Paypoint','0','1'],
            ['1','Pokerstars','0','1'],
            ['1','Popmoney','0','1'],
            ['1','Przelewy24','0','1'],
            ['1','Qiwi','0','1'],
            ['1','QNB smart wallet','0','1'],
            ['1','QQ Pay','0','1'],
            ['1','Quickteller','0','1'],
            ['1','Rapid Transfer','0','1'],
            ['1','Rapipago','0','1'],
            ['1','Remita','0','1'],
            ['1','Remitly','0','1'],
            ['1','Revolut','0','1'],
            ['1','Rocket Remit','0','1'],
            ['1','Safaricom Bonga Points','0','1'],
            ['1','Sendwave Wallet','0','1'],
            ['1','Simbapay','0','1'],
            ['1','Simple Bank App','0','1'],
            ['1','Skrill','0','1'],
            ['1','Slydepay Wallet','0','1'],
            ['1','SoFi Money Instant Transfer','0','1'],
            ['1','Sofort','0','1'],
            ['1','SolidTrust Pay','0','1'],
            ['1','Spektra','0','1'],
            ['1','Square up','0','1'],
            ['1','Straight Talk Reload','0','1'],
            ['1','Stripe','0','1'],
            ['1','Swish','0','1'],
            ['1','T-kash','0','1'],
            ['1','Tarjeta PAGO24','0','1'],
            ['1','Tarjeta PREX','0','1'],
            ['1','Tarjeta UALA','0','1'],
            ['1','Tele2','0','1'],
            ['1','Tigo Money','0','1'],
            ['1','Tigo Pesa','0','1'],
            ['1','Tikkie','0','1'],
            ['1','Toss Wallet','0','1'],
            ['1','Tpaga','0','1'],
            ['1','TransferGo','0','1'],
            ['1','TrueMoney','0','1'],
            ['1','UGO Pay','0','1'],
            ['1','Uhuru','0','1'],
            ['1','UnionPay (App)','0','1'],
            ['1','Uphold','0','1'],
            ['1','VBank','0','1'],
            ['1','Venmo','0','1'],
            ['1','VIABUY Card2Card Transfer','0','1'],
            ['1','ViettelPay','0','1'],
            ['1','VoguePay','0','1'],
            ['1','Wapipay','0','1'],
            ['1','Wari','0','1'],
            ['1','Wave Mobile Wallet','0','1'],
            ['1','WebMoney','0','1'],
            ['1','WeChat Pay','1','1'],
            ['1','Wells Fargo SurePay','0','1'],
            ['1','Wise (TransferWise)','0','1'],
            ['1','Xago','0','1'],
            ['1','Xoom Money Transfer','0','1'],
            ['1','YONO','0','1'],
            ['1','YooMoney','0','1'],
            ['1','ZaloPay','0','1'],
            ['1','Zelle Pay','1','1'],
            ['2','Bank Transfer','1','1'],
            ['2','Domestic Wire Transfer','1','1'],
            ['2','Faster Payment System (FPS)','1','1'],
            ['2','IMPS Transfer','1','1'],
            ['2','Interac Online','0','1'],
            ['2','International Wire Transfer (SWIFT)','1','1'],
            ['2','PayID','0','1'],
            ['2','SEPA','0','1'],
            ['2','UPI Transfer','1','1'],
            ['2','Zengin System','0','1'],
            ['3', 'Adidas Gift Card','0','1'],
            ['3', 'AirBnb Gift Card','0','1'],
            ['3', 'Amazon Gift Card','1','1'],
            ['3', 'AMC Theaters Gift Card','0','1'],
            ['3', 'American Apparel Gift Card','0','1'],
            ['3', 'American Express Gift Card','0','1'],
            ['3', 'Apple Gift Card (US only)','0','1'],
            ['3', 'Apple Store Gift Card','0','1'],
            ['3', 'Applebee\'s Restaurant Gift Card','0','1'],
            ['3', 'Asos Gift Card','0','1'],
            ['3', 'AT&T Gift Card','0','1'],
            ['3', 'Barnes & Noble Gift Card','0','1'],
            ['3', 'Bed Bath & Beyond Gift Card','0','1'],
            ['3', 'Best Buy Gift Card','0','1'],
            ['3', 'Bitrefill Balance Cards','0','1'],
            ['3', 'Blizzard Gift Card','0','1'],
            ['3', 'Booking.com gift cards','0','1'],
            ['3', 'Boost Mobile','0','1'],
            ['3', 'Cabela\'s E-Gift Code','0','1'],
            ['3', 'Calvin Klein Gift Card','0','1'],
            ['3', 'CASHlib Vouchers','0','1'],
            ['3', 'Chili\'s Restaurant Gift Card','0','1'],
            ['3', 'China Telecom Card','0','1'],
            ['3', 'Coles Gift Card','0','1'],
            ['3', 'Colourpop Gift Card','0','1'],
            ['3', 'Costco Cash Card','0','1'],
            ['3', 'Cracker Barrel Gift Card','0','1'],
            ['3', 'CVS Gift Card','0','1'],
            ['3', 'Dell Gift Card','0','1'],
            ['3', 'Delta Air Line Gift Card','0','1'],
            ['3', 'DENT','0','1'],
            ['3', 'Disney Gift Cards','0','1'],
            ['3', 'DMM Prepaid Card','0','1'],
            ['3', 'Domino\'s Pizza Gift Card','0','1'],
            ['3', 'DoorDash Gift Card','0','1'],
            ['3', 'Dunkin\' Donuts Card','0','1'],
            ['3', 'Eastbay Gift Card','0','1'],
            ['3', 'eBay Gift Card','1','1'],
            ['3', 'eGifter.com code','0','1'],
            ['3', 'Etsy','0','1'],
            ['3', 'Everlane Gift card','0','1'],
            ['3', 'Fandango Gift Card','0','1'],
            ['3', 'Finish Line Gift Card','0','1'],
            ['3', 'Flexepin Gift Card','0','1'],
            ['3', 'Flipkart e-Gift Voucher','0','1'],
            ['3', 'Footlocker Sports Gift Card','0','1'],
            ['3', 'Forever 21 Gift Card','0','1'],
            ['3', 'FreshDirect Gift Card','0','1'],
            ['3', 'G2A Gift Card','0','1'],
            ['3', 'GameStop Gift Card','0','1'],
            ['3', 'Gift Cards (Miscellaneous  Retailers)','0','1'],
            ['3', 'Giftcards.nl Redeem choice card','0','1'],
            ['3', 'Google Play Gift Card','1','1'],
            ['3', 'Groupon Gift Card','0','1'],
            ['3', 'Grubhub Gift Card','0','1'],
            ['3', 'H&M Gift Card','0','1'],
            ['3', 'Happy card gift cards','0','1'],
            ['3', 'Home Depot Gift Card','0','1'],
            ['3', 'Hotels.com Gift Card','0','1'],
            ['3', 'HULU Gift Card','0','1'],
            ['3', 'Hyatt eGift Card','0','1'],
            ['3', 'IHOP Gift Card','0','1'],
            ['3', 'IKEA Gift Card','0','1'],
            ['3', 'iTunes Gift Card','1','1'],
            ['3', 'Jason\'s Deli Gift Cards','0','1'],
            ['3', 'JCPenney Gift Card','0','1'],
            ['3', 'JD.com gift cards','0','1'],
            ['3', 'Kohls Store Gift Card','0','1'],
            ['3', 'Lowe\'s Gift Card','0','1'],
            ['3', 'Lyft Gift Card','0','1'],
            ['3', 'Macy\'s Gift Card','0','1'],
            ['3', 'MasterCard Gift Card','0','1'],
            ['3', 'Microsoft Gift card','0','1'],
            ['3', 'MoneyPak','0','1'],
            ['3', 'Myer Gift Card','0','1'],
            ['3', 'Neosurf Gift Card','0','1'],
            ['3', 'Netflix Gift Card','0','1'],
            ['3', 'Newegg Gift Card','0','1'],
            ['3', 'Nike Gift Card','0','1'],
            ['3', 'Nintendo eShop Digital Card / Gift card','0','1'],
            ['3', 'Nordstrom Gift Card','0','1'],
            ['3', 'Offgamers.com Gift Card','0','1'],
            ['3', 'Office Depot Gift Card','0','1'],
            ['3', 'Old Navy E Gift Card','0','1'],
            ['3', 'Olive Garden Restaurant Gift Card','0','1'],
            ['3', 'OneVanilla VISA/MasterCard Gift Card','1','1'],
            ['3', 'Papa Johns Gift Card','0','1'],
            ['3', 'PCS Prepaid Cash Services','0','1'],
            ['3', 'Pizza Hut Gift Card','0','1'],
            ['3', 'PlayStation Network Gift Card','0','1'],
            ['3', 'Quiksilver Gift Card','0','1'],
            ['3', 'Razer Gold Gift Card','0','1'],
            ['3', 'Reebok Gift Card','0','1'],
            ['3', 'Reloadit by Netspend','0','1'],
            ['3', 'Restaurant Gift Cards (Various Retailers)','0','1'],
            ['3', 'Riot Points League of Legends','0','1'],
            ['3', 'Roblox Game Card','0','1'],
            ['3', 'Safeway Gift Card','0','1'],
            ['3', 'Saks Fifth Avenue Gift Card','0','1'],
            ['3', 'Sears Gift Card','0','1'],
            ['3', 'Sephora Gift Card','0','1'],
            ['3', 'Skype Credits','0','1'],
            ['3', 'Southwest Airlines Gift Card','0','1'],
            ['3', 'Spotify Gift Card','0','1'],
            ['3', 'Staples Gift Card','0','1'],
            ['3', 'Starbucks Card','0','1'],
            ['3', 'Steam Wallet Gift Card','1','1'],
            ['3', 'Subway Gift Card','0','1'],
            ['3', 'T-Mobile Refill','0','1'],
            ['3', 'Target Gift Card','0','1'],
            ['3', 'Target VISA Gift Card','0','1'],
            ['3', 'Ticket Premium Gift Card','0','1'],
            ['3', 'TicketMaster Gift Card','0','1'],
            ['3', 'Twitch Gift Card','0','1'],
            ['3', 'Uber Eats','0','1'],
            ['3', 'Uber Gift Card','0','1'],
            ['3', 'Ulta Gift Card','0','1'],
            ['3', 'United Airlines Gift Card','0','1'],
            ['3', 'Victoria\'s Secret Gift Card','0','1'],
            ['3', 'VISA Gift Card','0','1'],
            ['3', 'Walmart China Card','0','1'],
            ['3', 'Walmart Gift Card','0','1'],
            ['3', 'Walmart Visa Gift Card','0','1'],
            ['3', 'Whole Foods Market Gift Card','0','1'],
            ['3', 'Xbox Gift Card','0','1'],
            ['3', 'Zappos Gift Card','0','1'],
            ['4', 'Amazon Cash','0','1'],
            ['4', 'Bancolombia Cash Deposit','1','1'],
            ['4', 'Bitcoin ATM','0','1'],
            ['4', 'Cardless Cash','1','1'],
            ['4', 'Cash By Mail','0','1'],
            ['4', 'Cash Deposit to Bank','1','1'],
            ['4', 'Cash in Person','0','1'],
            ['4', 'Cashier\'s check','0','1'],
            ['4', 'Check','0','1'],
            ['4', 'EzRemit','0','1'],
            ['4', 'MoneyGram','1','1'],
            ['4', 'OXXO','0','1'],
            ['4', 'Postal Money Order','0','1'],
            ['4', 'RIA Money Transfer','0','1'],
            ['4', 'Transfast','0','1'],
            ['4', 'Vodafone Cash Payment','1','1'],
            ['4', 'Western Union','1','1'],
            ['4', 'Xpress Money Service','0','1'],
            ['5', 'AccountNow Prepaid Card','0','1'],
            ['5', 'Akimbo','0','1'],
            ['5', 'American Express Card','1','1'],
            ['5', 'ANY Credit/Debit Card','1','1'],
            ['5', 'Bluebird American Express','1','1'],
            ['5', 'Card.com Transfer','0','1'],
            ['5', 'Discover Credit Cards','0','1'],
            ['5', 'GreenDot Card','1','1'],
            ['5', 'Kroger Recharge Card','0','1'],
            ['5', 'Kroger to Kroger Prepaid','0','1'],
            ['5', 'Mango Card2Card','0','1'],
            ['5', 'MyVanilla Prepaid Card','0','1'],
            ['5', 'Paysafecard','1','1'],
            ['5', 'PostePay','0','1'],
            ['5', 'Prepaid Debit Card','0','1'],
            ['5', 'READYdebit Prepaid Card','0','1'],
            ['5', 'RushCard prepaid Visa','0','1'],
            ['5', 'Serve to Serve','0','1'],
            ['5', 'Visa Debit/Credit Card','0','1'],
            ['5', 'Walmart MoneyCard','1','1'],
            ['6', 'Bilira(TRYB)','0','1'],
            ['6', 'Bitcoin Cash BCC/BCH','1','1'],
            ['6', 'Bitcoin Gold BTG','0','1'],
            ['6', 'Bitgold','0','1'],
            ['6', 'BitShares BTS','0','1'],
            ['6', 'BRZ','0','1'],
            ['6', 'ChainLink','0','1'],
            ['6', 'CNHC','0','1'],
            ['6', 'Credits (CS)','0','1'],
            ['6', 'DOC','0','1'],
            ['6', 'Dogecoin DOGE','1','1'],
            ['6', 'EOS','0','1'],
            ['6', 'Ethereum Classic ETC','0','1'],
            ['6', 'Ethereum ETH','0','1'],
            ['6', 'IDRT','0','1'],
            ['6', 'IOTA-MIOTA','0','1'],
            ['6', 'Litecoin LTC','1','1'],
            ['6', 'Namecoin NMC','0','1'],
            ['6', 'Nano','0','1'],
            ['6', 'NEM','0','1'],
            ['6', 'NEO','0','1'],
            ['6', 'NGNT','0','1'],
            ['6', 'Paxos Gold (PAXG)','0','1'],
            ['6', 'Paxos Standard (PAX)','0','1'],
            ['6', 'Peercoin PPC','0','1'],
            ['6', 'Polkadot (DOT)','0','1'],
            ['6', 'Qtum','0','1'],
            ['6', 'Siacoin SC','0','1'],
            ['6', 'Steem Coin STEEM','0','1'],
            ['6', 'Stellar Lumens XLM','1','1'],
            ['6', 'Stratis STRAX','0','1'],
            ['6', 'Tether USDT','1','1'],
            ['6', 'TRON TRX','1','1'],
            ['6', 'TrueUSD (TUSD)','0','1'],
            ['6', 'USDC','0','1'],
            ['6', 'VeChain VET','0','1'],
            ['6', 'Waves Coin WAVES','0','1'],
            ['7', 'Amazon Wishlist','0','1'],
            ['7', 'Cars','0','1'],
            ['7', 'Game Items','0','1'],
            ['7', 'Gold','0','1'],
            ['7', 'Google Pay- Gold Locker (MMTC-PAMP)','0','1'],
        ];

        foreach($paymentMethods as $key=>$value){
            $methodInsert = [                
                'payment_category_id' => $value[0],
                'name' => $value[1],
                'is_popular' => $value[2],
                'is_active' => $value[3],
            ];
            DB::table('payment_methods')->insert($methodInsert);
        }
    }
}
